// Generated by CoffeeScript 1.10.0
(function() {
  var amp, osc;

  osc = audioContext.createOscillator();

  amp = audioContext.createGain();

  osc.type = "square";

  osc.frequency.setValueAtTime(987.7666, 0);

  osc.frequency.setValueAtTime(1318.5102, 0.075);

  osc.start(0);

  osc.stop(2);

  osc.connect(amp);

  amp.gain.setValueAtTime(0.25, 0);

  amp.gain.setValueAtTime(0.25, 0.075);

  amp.gain.linearRampToValueAtTime(0, 2);

  amp.connect(audioContext.destination);

}).call(this);
