// Generated by CoffeeScript 1.10.0
(function() {
  var LoadedBuffer, a, b, c, fs, i, j, k, l, m, o;

  fs = require("fs");

  LoadedBuffer = (function() {
    function LoadedBuffer(filename) {
      this.filename = filename;
    }

    LoadedBuffer.prototype.init = function() {};

    LoadedBuffer.prototype.play = function(n) {
      return audioContext.decodeAudioData(this.filename).then(function(decodedData) {
        this.decodedData = decodedData;
        this.source = audioContext.createBufferSource();
        this.source.buffer = this.decodedData;
        this.source.connect(audioContext.destination);
        this.source.start(n);
        return this.source.onended = x;
      });
    };

    return LoadedBuffer;

  })();

  a = new LoadedBuffer(fs.readFileSync("./drum_bass_hard.wav"));

  b = new LoadedBuffer(fs.readFileSync("./drum_cymbal_closed.wav"));

  c = new LoadedBuffer(fs.readFileSync("./drum_snare_hard.wav"));

  for (i = l = 0; l <= 8; i = l += 2) {
    a.play(i);
  }

  for (j = m = 0; m <= 8; j = m += 0.5) {
    b.play(j);
  }

  for (k = o = 1; o <= 8; k = o += 2) {
    c.play(k);
  }

}).call(this);
