// Generated by CoffeeScript 1.10.0
(function() {
  var bass, fs, i, j, play;

  fs = require("fs");

  bass = fs.readFileSync("./drum_bass_hard.wav");

  play = function(n) {
    return audioContext.decodeAudioData(bass).then(function(decodedData) {
      var buf, source;
      buf = new BufferLoader();
      source = audioContext.createBufferSource();
      source.buffer = decodedData;
      source.connect(audioContext.destination);
      return source.start(n);
    });
  };

  for (i = j = 0; j <= 10; i = j += 2) {
    play(i);
  }

}).call(this);
