// Generated by CoffeeScript 1.10.0
(function() {
  var AudioBuffer, amp, i, j, startstop;

  amp = audioContext.createGain();

  AudioBuffer = (function() {
    function AudioBuffer(pitch) {
      this.pitch = pitch;
      this.osc = audioContext.createOscillator();
      this.osc.type = "sawtooth";
      this.osc.frequency.setValueAtTime(this.pitch, 0);
      this.osc.connect(amp);
    }

    return AudioBuffer;

  })();

  startstop = function(o, x) {
    o.osc.start(x);
    return o.osc.stop(x + 2);
  };

  for (i = j = 0; j <= 12; i = j += 2) {
    startstop(new AudioBuffer(440 + i * 10), i);
  }

  amp.connect(audioContext.destination);

}).call(this);
