// Generated by CoffeeScript 1.10.0

/*
Author: Jason Gwartz
2016
 */
var SoundNode, Wrapper, for_loop, if_conditional,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

Wrapper = (function() {
  Wrapper.instances = [];

  function Wrapper(name, check) {
    this.name = name;
    this.check = check;
    Wrapper.instances.push(this);
    this.html = "<div class=\"node node-wrapper\" id=\"" + this.name + "\">\n  <h2>" + this.name + "</h2>\n</div>";
  }

  return Wrapper;

})();

if_conditional = new Wrapper("If", function(condition_to_check, input) {
  var i, j, len, ref;
  input = (function() {
    var j, len, ref, results;
    ref = input.replace(/\D/g, " ").split(" ");
    results = [];
    for (j = 0, len = ref.length; j < len; j++) {
      i = ref[j];
      results.push(parseInt(i));
    }
    return results;
  })();
  if (condition_to_check === "phrase") {
    return ref = phrase + 1, indexOf.call(input, ref) >= 0;
  } else if (condition_to_check === "beat") {
    for (j = 0, len = input.length; j < len; j++) {
      i = input[j];
      this.sound_node.instrument.play(i);
    }
    return true;
  }
});

for_loop = new Wrapper("For", function(number_loops, loop_block) {
  if (loop_block === "phrase") {
    return pass();
  } else if (loop_block === "bars") {
    return pass();
  } else if (loop_block === "beats") {
    return pass();
  }
});

SoundNode = (function() {
  SoundNode.tray_instances = [];

  SoundNode.canvas_instances = [];

  function SoundNode(instrument) {
    this.instrument = instrument;
    this.id = this.instrument.name;
    this.wrappers = [];
    this.html = "<div class=\"node node-sample\" id=\"" + this.id + "\">\n  <h2>" + this.id + "</h2>\n</div>";
  }

  SoundNode.prototype.get_wrappers = function() {
    var w;
    w = $("" + this.id).parentsUntil("#node-canvas");
    return console.log(w);
  };

  SoundNode.prototype.phrase_eval = function() {
    var j, len, results, w;
    results = [];
    for (j = 0, len = wrappers.length; j < len; j++) {
      w = wrappers[j];
      results.push(w.check());
    }
    return results;
  };

  return SoundNode;

})();
