// Generated by CoffeeScript 1.10.0
var ui_init;

ui_init = function() {
  console.log("init");
  return $(".input-group").each(function(index, element) {
    var btn, name;
    btn = $(element).find("button");
    name = $(element).find("input").attr("id");
    return btn.on("click", function() {
      var i, x;
      i = ((function() {
        var j, len, results;
        results = [];
        for (j = 0, len = instruments.length; j < len; j++) {
          x = instruments[j];
          if (x.name === name) {
            results.push(x);
          }
        }
        return results;
      })())[0];
      console.log(i);
      i.is_live = !i.is_live;
      console.log(i);
      return $(btn).button('reset');
    });
  });
};
